### ISSUE TITLE
fia-AK loadouts

### ISSUE THREAD

**Issue by costno** [Raptoer/F3#10]
SK notes that there is some issue with randomization and this loadout...

**Comment by ninjaProtocol** [comment]
in `f_assignGear_fiaAK.sqf`
```
// Standard Carabineer (Medic, Rifleman (AT), MAT Gunner, MTR Gunner, Carabineer)
_carbine = "arifle_AKS_F";
```
in light/standard f_assignGear_fiaAK_standard.sqf
```
// Include the loadouts for vehicles and crates:
#include "f_assignGear_fia_v.sqf";
```
in f_assignGear_fia_v.sqf
```
_unit addWeaponCargoGlobal [(_carbine call BIS_fnc_selectRandom), 2];
```
...in multiple places.

Basically, it expects and array and gets a string.

Snippers had long ago suggested shifting the `selectRandom` (i think that needs to be changed to the engine command anyway) to the base loadout file itself for all the loadouts (i.e. `f_assignGear_fiaAK.sqf` etc.) and thus avoiding this issue in the vehicle gear file.

(on that note, couldn't we just have one vehicle gear file if we did that?)
