### ISSUE TITLE
ws_fnc: Remove cache and check for other unexpected changes.

### ISSUE THREAD

**Issue by SamLex** [Raptoer/F3#102]
The cache functions were removed and then re-added at some point without comment. They should probably be removed again and any other unexpected changes fixed.

**Comment by ninjaProtocol** [comment]
Out of curiosity, what is the ws_fnc cache for, anyway?

**Comment by SamLex** [comment]
At a glance, it's a straight copy of (what used to be) F3's...

So this issue and #115 compliment each other quite well :P

(assuming they are actually the same).

**Comment by shadow-fa** [comment]
As far as I know it existed before, but the f3 cache component is now an almost exact copy of it.
(But the ws_fnc cache was never actually used since f3 absorbed it)

**Comment by SamLex** [comment]
#104 has been merged to resolve this issue. Will close this issue once 3.5.1 is 'feature-complete' and all merged issues can be tested at once.
