### ISSUE TITLE
Wiki: Create a guide for updating a mission from 3.4.1 to 3.5

### ISSUE THREAD

**Issue by SamLex** [Raptoer/F3#103]

**Comment by SamLex** [comment]
I'm considering closing this since the working de-facto at the moment is send the mission to me to update.
Opinion @shadow-fa?

**Comment by shadow-fa** [comment]
We could link the updater script somewhere, but yeah, I agree.

**Comment by SamLex** [comment]
Added a brief page to the wiki linking to the tool:
https://github.com/Raptoer/F3/wiki/Updating-Missions-%28Advanced%29
