### ISSUE TITLE
WASD causes group focusing in spectator?

### ISSUE THREAD

**Issue by SamLex** [Raptoer/F3#121]
WASD reportedly causes group focusing in spectator, similar to in the old spectator script. This should be investigated and mitigation if possible, and reported to BI if mitigation is not possible.

**Comment by SamLex** [comment]
Bit of testing in "Winning the Game" v1: this only seems to happen if you mouse over the sidebar, seems less bug, more unexplained feature

**Comment by shadow-fa** [comment]
Can confirm the behaviour.
I think this issue can be closed once this is documented in the spectator components wiki page: <https://github.com/Raptoer/F3/wiki>
