### ISSUE TITLE
Remove disableTIEquipment from template vehicle inits

### ISSUE THREAD

**Issue by NikkoJT** [Raptoer/F3#129]
Since the addition of the Disable Thermals component, the `this disableTIEquipment true` code on the Platoons vehicles is redundant. It may also cause confusion, as it would cause a vehicle to have its thermals disabled even if excluded from the Disable Thermals component. Simple solution: remove the code from the vehicle init lines.

@shadow-fa

**Comment by shadow-fa** [comment]
Fixed in PR #128
