### ISSUE TITLE
disableThermals for zeus placed vehicles

### ISSUE THREAD

**Issue by shadow-fa** [Raptoer/F3#135]
Add `disableTIEquipment` to every zeus placed vehicle if the disableThermals component is active.
Similar to how setAISkill is handled:
https://github.com/Raptoer/F3/blob/f21f1a696d5a61460d726adba6e7fdc5785f5f70/f/zeus/fn_zeusInit.sqf#L69-L72

**Comment by NikkoJT** [comment]
Seems reasonable.

My only question is whether it would be possible for the Zeus to override it on any given individual object, so that they can grant players thermal-enabled vehicles, or provide a replacement if a thermal-enabled vehicle gets eaten by Arma.

**Comment by SamLex** [comment]
A Zeus with Achilles (which we highly recommend) can toggle thermals, both with the IR equipment module (I believe) or the scripting module.

**Comment by shadow-fa** [comment]
Currently there's two places where we call zeus-related code:
In every zeus' init field:
https://github.com/Raptoer/F3/blob/d15923766844aa66f837f5cbcaf87fb548b88dde/mission.sqm#L2235
and in in the admin briefing:
https://github.com/Raptoer/F3/blob/d15923766844aa66f837f5cbcaf87fb548b88dde/f/briefing/f_briefing_admin.sqf#L103

The admin briefing calls `zeusInit`, whereas the init fields adds a CuratorObjectPlaced event handler (which `zeusInit` also does) and adds all `playableUnits`.

To reduce the number of places with zeus related code and to maker future code changes easier, 
I propose replacing the init fields with a call to `zeusInit` and change `zeusInit` accordingly to make sure it behaves the same. 

Alternatively we could also move it to `init.sqf` to make it more visible to missionmakers. This way we could also add some comments to show how a missionmaker would add additional units to the zeus. (e.g. all pre-placed AI/vehicles)

**Comment by SamLex** [comment]
Reducing call points by always using `zeusInit` sounds like a great idea. I also like the idea of moving the call from init fields to `init.sqf` (or have a new `zeusInitAll` that is called from `init.sqf`, either way).

**Comment by NikkoJT** [comment]
Working in 3.5.2 test mission.
