### ISSUE TITLE
JIP issues

### ISSUE THREAD

**Issue by shadow-fa** [Raptoer/F3#142]
Currently not all components are JIP-safe, this should be changed. Because reconnects do happen and it would be nice if this wouldn't break anything.

List of components with known JIP issues:

#### Zeus
- blank black screen is shown (BI Bug?)
   issue: the curator is no longer linked with the player when JIP.
   https://feedback.bistudio.com/T119801
   https://feedback.bistudio.com/T123886
   un-assigning and re-assigning the curator does work, but fnc_zeusInit only gets called by the curator (module) and we don't know which player was assigned to which curator object. Additionally we would need to make sure the event handlers don't break.

#### ~~Fireteam Member Markers~~
- ~~No colors. Fixed in #156. Merged~~

#### ~~setTeamColours~~
- ~~since Arma 3 1.62 `assignTeam` has global effect, which leads to the "problem" that teamcolors are reset when someone reconnects. Fixed in #163. Merged~~

#### ~~groupMakers~~
 - ~~Groups that didn't exist when the mission started (no ai in slot) don't have a group marker. But they probably should have markers to handle reinforcements on the fly. Fixed in #182.~~

Ideally we should check all components for any JIP-related issues and document them here.

**Comment by SamLex** [comment]
**Test Plan**
Testing in 3.5.2 test mission with two players

1. Check JIP-ers can see team colours
   1. 2 players in FT
   2. One leaves and reconnects
   3. Verify they can see team colours on STHUD
2. Check JIP-ers don't reset team colours
   1. As above but modify team colours before second player rejoins
3. Check JIP'ing groups have markers
   1. 2 players in FT
   2. One leaves and reconnects in an unslotted group
   3. Verify both players can see a marker for that group
