### ISSUE TITLE
Use - or _ as a separator instead of . in the template folder name

### ISSUE THREAD

**Issue by NikkoJT** [Raptoer/F3#150]
The mission template folder currently looks like this:
> FA3.5.1-release-template.VR

It should be changed to:
> FA3-5-1-release-template.VR
> FA3_5_1-release-template.VR

This is because the additional periods in the folder name cause A3 to fail to load the mission. When creating new missions this can be avoided by renaming a copy of the template folder before starting, but it's a pain when trying to open the template to copy units into an existing mission.

**Comment by shadow-fa** [comment]
Can be closed since it's now documeted in the release checklist:
<https://github.com/Raptoer/F3/wiki/Release-Checklist>
