### ISSUE TITLE
Spectator Slot Briefing

### ISSUE THREAD

**Issue by SamLex** [Raptoer/F3#151]
Spectator slots currently get a default briefing (or the Zeus briefing, not sure which). It would be good if they got the briefing of the active player side or, failing that, no briefing at all.

**Comment by shadow-fa** [comment]
This would require the concept of an `active faction`.
Because of the number of possible factions/briefings and the fact that multiple factions can be active at the same time, this would add too much complexity and I think no briefing should be shown instead.

**Comment by NikkoJT** [comment]
PR #161 seems to be working correctly. In the dev version, spectators see no briefing, with no error message. Zeus still sees a briefing. The F3 Admin briefing tab is still available for spectators.

**Comment by SamLex** [comment]
Great, thanks @NikkoJT. I'll close this issue when FA3.5.2 is released.
