### ISSUE TITLE
Virtual Entity Components

### ISSUE THREAD

**Issue by SamLex** [Raptoer/F3#152]
Spectator and Zeus slot currently have components such as fireteam markers and nametags unnecessarily enabled, which can lead to weird results such as [this](https://cdn.discordapp.com/attachments/104982724762157056/424655017723559946/107410_20180317194539_1.png). These components and any others that are not needed for these virtual entities should be disabled for those slots.

**Comment by NikkoJT** [comment]
PR #160 seems to be working properly. Zeus and Spectator players no longer see fireteam member markers. They don't see nametags either, although I'm not sure they ever actually did. No apparent breakages; players still see nametags and FT markers as expected.

**Comment by SamLex** [comment]
Great, thanks @NikkoJT. I'll close this issue when FA3.5.2 is released.
