### ISSUE TITLE
Re-add extra FAKs from old sws

### ISSUE THREAD

**Issue by shadow-fa** [Raptoer/F3#154]
With the old simple wounding system we had this:
https://github.com/ferstaberinde/F3/blob/6877a4c42c4e04dcd9fe1614784f852f7c69812e/init.sqf#L16-L17

This is currently gone and now everyone has 2 FAKs less with 3.5.x missions (compared to pre 3.5).

I think this functionality should be re-added (either in `medical` or `assignGear`). 
`assignGear` (after the faction-specific gear has been applied) would be a good place to re-add the FAKs.

**Comment by SamLex** [comment]
**Test Plan**
Testing in 3.5.2 test mission

1. Spot check random units to verify number of FAKs
   1. Reference 3.4.1 missions and code
