### ISSUE TITLE
AssignGear - reorganise aircrew classes

### ISSUE THREAD

**Issue by NikkoJT** [Raptoer/F3#165]
Currently we have three separate assignGear classes for helicrew - pilot, copilot, and gunner. With our current circumstances this is unnecessary, as there's no reason why all crew shouldn't have the same gear.

A single helicopter crew class (hc) would be fine. All crew members would have repair, removing the current silliness of slotting a copilot instead of a pilot when the helo is being flown solo.

Alongside this, we should add a jet pilot class using the new Jet Pilot helmet and coveralls. This could be used in a new CAS template unit.

DarkChozo proposes that the new aircrew classes could carry their weapons in their backpacks by default.

**Comment by ninjaProtocol** [comment]
> All crew members would have repair, removing the current silliness of slotting a copilot instead of a pilot when the helo is being flown solo.

While this is true (silliness), I'm assuming they're distinct to avoid cases of both pilot and co-pilot dismounting to repair when there used to be enough people. The change as you suggested is likely the right thing to do at this point, but there's just something making me hesitate that I can't put my finger on.

**Comment by NikkoJT** [comment]
The Pilot and Crew Chief assignGear classes in the current version both have repair anyway. Out of the three classes, the only one that doesn't have repair is the Crew, which I believe is only actually used in helicopters with door gunners (i.e. almost never).

**Comment by shadow-fa** [comment]
When implementing this, we must not forget to remove the ` (repair)` from the slot descriptions.

**Comment by SamLex** [comment]
**Test Plan**
Testing in 3.5.2 test mission

1. Spot check helo crews gear and ensure it is identical
