### ISSUE TITLE
Platoons - add CAS1 element

### ISSUE THREAD

**Issue by NikkoJT** [Raptoer/F3#166]
In conjunction with the new jet pilot class proposed in issue #165, we should add a template CAS1 element to all factions.

The element would consist of one Jet Pilot and:
NATO: A-164 Wipeout
AAF: A-143 Buzzard
CSAT: To-199 Neophron

**Comment by ninjaProtocol** [comment]
Just need to make sure that the pilot starts outside the plane, since AI pilots will always try and take off.

**Comment by NikkoJT** [comment]
CAS1 correctly added in 3.5.2 test mission. Except for using the Helicopter Pilot base class? Not sure if this is intended, I believe there is a Pilot or Jet Pilot base class for all CAS-capable factions.

**Comment by SamLex** [comment]
Hmm, I'll need to look into this, they are getting assigned "jp" in the mission.sqm. They are very similar loadouts?

**Comment by NikkoJT** [comment]
The F3 loadout is correct, I'm referring to the base unit the F3 loadout is being applied to.
(I'm pretty sure it doesn't make any actual difference but it does seem odd)

**Comment by SamLex** [comment]
Ah right, I see. That is quite odd. Given, however, it isn't breaking anything I don't want to hold up 3.5.2. So I'll create a new issue to fix this for 3.5.3 that will get done in 3.5.2 if we do another RC.
