### ISSUE TITLE
[Discuss] Rename DC element to XO

### ISSUE THREAD

**Issue by NikkoJT** [Raptoer/F3#168]
Currently we have a Deputy Commander element (which we never use). I propose that this element be renamed (not changed in any other way) to Executive Officer, or XO.

Points:
-> better reflects real-world unit structure
-> sounds cooler
-> better reflects the expected role of the unit
-> may encourage the element to be used more, particularly thinking of tank missions
-> no change in actual role so no need to change it in older missions
-> no real need to change assignGear classes, only groupID, mapMarkers and slotting role

But:
-> some people like "DC"
-> not particularly important
-> effort (although not much effort)

**Comment by darkChozo** [comment]
An alternative would be Second in Command (2i/c or 2IC), which is the British equivalent of the American XO.

Also, it might be worth considering removing DC as a separate group entirely, as it's currently almost never used and is awkward from a comms perspective. Having DC be in the command group would let them communicate without having to pollute other channels, especially considering that any mission with a DC will likely have other people in HQ as well.

**Comment by NikkoJT** [comment]
While I was thinking about this I did consider the 2IC option. There were a couple of problems with it - first, it's longer. XO and DC are about the same, verbally, but 2IC is more complex. The other problem is that the rest of our platoons are (approximately) US-based, and NATO in particular is explicitly composed of US troops.

**Comment by costno** [comment]
I don't see a purpose in changing the name. We barely use the slot regardless and I see no reason to introduce a new name that won't be shared in previous missions containing the DC. Unless we actually go back through those and update them. The only positive change I see from using the word XO, or even 2iC, would be it sounds cooler.  I for one have a better understanding of the role of a DC through FA than I do of the role of XO in real life militaries. My understanding of the XO is just Saul Tigh

**Comment by shadow-fa** [comment]
I completely agree with costno. I don't think we gain anything by changing the name, it's just additional effort and older missions would have to be updated to avoid inconsistent naming.

**Comment by ninjaProtocol** [comment]
Yep, don't see the point of renaming DC. All our forum pages that explain the platoon structure call the role "DC" as well, so that would introduce even more confusion/work for little to no gain.

**Comment by SamLex** [comment]
I'm going to close this now since the general consensus seems to be that this is not needed.
