### ISSUE TITLE
Remove JIP notification from description.ext

### ISSUE THREAD

**Issue by SamLex** [Raptoer/F3#169]
description.ext contains a Notification block that was't removed when the JIP module was: https://github.com/Raptoer/F3/blob/d15923766844aa66f837f5cbcaf87fb548b88dde/description.ext#L100-L107

**Comment by shadow-fa** [comment]
Note: This block is used for the groupJoin component. Is has been renamed to reflect that behaviour/usage in #171.

**Comment by NikkoJT** [comment]
This appears to have been changed successfully. The notification block has been renamed in description.ext, and joining a group produces the notification as expected without any errors.

**Comment by SamLex** [comment]
Great, thanks @NikkoJT. I'll close this issue when FA3.5.2 is released.
