### ISSUE TITLE
"Use mission default" should be the default mission conditon

### ISSUE THREAD

**Issue by SamLex** [Raptoer/F3#170]
For a number of the mission condition parameters in description.ext, the default value is something other than "Use mission default". This should be changed so that the mission conditions module does not override the editor settings unless a missionmaker or host changes the parameter

**Comment by shadow-fa** [comment]
Note:
https://github.com/Raptoer/F3/blob/d15923766844aa66f837f5cbcaf87fb548b88dde/stringtable.xml#L86-L87
and
https://github.com/Raptoer/F3/blob/d15923766844aa66f837f5cbcaf87fb548b88dde/stringtable.xml#L126-L127
are not consistent.

**Comment by NikkoJT** [comment]
As noted in comment on #172, while Weather and Time parameters use the "Use mission setting/s" phrasing, Fog and Wind parameters call it "Use default" instead. 

The actual issue (using the mission setting by default) was correctly fixed by PR 172, this is just a string issue.

**Comment by SamLex** [comment]
@shadow-fa Could you fix the inconsistent strings? Probably changing all to using "Use mission setting"

**Comment by shadow-fa** [comment]
Done in #180

**Comment by SamLex** [comment]
Looks like f_param_fog and f_param_wind in description.ext use a hard coded "Use default" rather than the stringtable "Use mission setting".
https://github.com/Raptoer/F3/blob/d15923766844aa66f837f5cbcaf87fb548b88dde/description.ext#L176

These should be changed to reference the stringtable.

**Comment by shadow-fa** [comment]
Done in #180

**Comment by NikkoJT** [comment]
Confirmed correct in 3.5.2 test mission.
