### ISSUE TITLE
Investigate potential AI skill issues

### ISSUE THREAD

**Issue by shadow-fa** [Raptoer/F3#177]
The AI seems deadlier lately, could it be because of a bug in 3.5.x's setAISkill?
We should investigate this and compare the effective ai skills (that were set by that component) pre- vs post-3.5.0.

edit: maybe it's just an issue with skill values that need tweaking due to the many game updates.
edit: related to #178

**Comment by NikkoJT** [comment]
Is this still relevant?

**Comment by costno** [comment]
Closing this, we updated AI skills in 3.5.6 or whenever so this is not still relevant.
