### ISSUE TITLE
Template: add all units to Zeus by default

### ISSUE THREAD

**Issue by NikkoJT** [Raptoer/F3#179]
Currently, the F3 template Zeus entities contain an init command which automatically makes playable units Zeus-editable.

This should be changed to add all units, playable or not. When playing as Zeus the first thing I do is add all units to Zeus using the FA admin mod, so I can see the mission's pre-placed units and work around or with them. This should be default behaviour, as we've had instances in the past of Zeuses not adding all units manually, and accidentally getting the players killed because they couldn't see pre-placed units.

The change is pretty simple - change the reference to "playableUnits" in the Zeus module init to refer to "allUnits". I've manually made this change in several missions that have been played live, and there don't seem to be any unexpected consequences.

**Comment by shadow-fa** [comment]
Thanks for creating the issue.
This will be fixed with #158.

**Comment by NikkoJT** [comment]
Appears to be fixed correctly in 3.5.2 test mission. Note that vehicles are not added, only their crews; this is acceptable and expected behaviour for the allUnits command.
