### ISSUE TITLE
NATO Gendarme Alpha Team out-of-order in slotting

### ISSUE THREAD

**Issue by SamLex** [Raptoer/F3#202]
The order of the Gendarme Alpha Team in the slotting screen is 
1. Gendarme
2. Sergeant
3. Gendarme
4. Gendarme

but should be
1. Sergeant
2. Gendarme
3. Gendarme
4. Gendarme

(See #199)

**Comment by NikkoJT** [comment]
Corrected in 3.5.2 test mission.
