### ISSUE TITLE
Replace _this select X with params

### ISSUE THREAD

**Issue by SamLex** [Raptoer/F3#24]
Provides better type checking and default value handling

**Comment by Raptoer** [comment]
Whoever decides to take this, be warned, there are 208 occurrences and it's not a simple find/replace.

**Comment by shadow-fa** [comment]
We should probably also replace all calls to `bis_fnc_param`

**Comment by shadow-fa** [comment]
`bis_fnc_param` has been fixed in #74

**Comment by shadow-fa** [comment]
Once PR's #99, #105, and #101 are merged,
I would suggest closing this issue as most occurrences have been dealt with.
Although we could still improve the typechecks as not all `params` actually use the `expectedDataTypes` and `expectedArrayCount` parameters yet.
I will leave this decision to @SamLex.

**Comment by SamLex** [comment]
Personally I'd prefer as many type checks as possible @shadow-fa

**Comment by shadow-fa** [comment]
Files that still have the old `_this select` syntax:
```
f_assignGear_aaf.sqf
f_assignGear_csat.sqf
f_assignGear_csatPacific.sqf
f_assignGear_ctrg.sqf
f_assignGear_fia.sqf
f_assignGear_fiaAK.sqf
f_assignGear_gendarmerie.sqf
f_assignGear_nato.sqf
f_assignGear_natoPacific.sqf
f_assignGear_syndikat.sqf

f_nametagDisableKey.sqf
```

**Comment by SamLex** [comment]
I'm happy leaving it the way it is until #94
