### ISSUE TITLE
Use Event Handlers for Dynamic View Distance

### ISSUE THREAD

**Issue by ninjaProtocol** [Raptoer/F3#37]
DVD runs in a constant loop with functionality can more elegantly shifted to event handlers. Additionally, it seems to randomly error out for units in "cargo" seats. Since it loops, the error stays there until the unit leaves the vehicle. This happens with ejection seats as well.

**Comment by SamLex** [comment]
PR #62

**Comment by SamLex** [comment]
#96 has been merged to resolve this issue. Will close this issue once 3.5.1 is 'feature-complete' and all merged issues can be tested at once.
