### ISSUE TITLE
_heavy category in f_assignGear_NATO and _CSAT

### ISSUE THREAD

**Issue by costno** [Raptoer/F3#4]
Something should be done!

**Comment by CSDGC** [comment]
Not necessarily "something should be done", just it should be noted that the category is there doing nothing, and only in certain factions' assignGear

**Comment by shadow-fa** [comment]
Note: This is referring to the unused variables `_light` and `_heavy`.
e.g. https://github.com/Raptoer/F3/blob/dfd6b74992659e41504723ef036a6c25b509ac13/f/assignGear/f_assignGear_nato.sqf#L241-L242

**Comment by SamLex** [comment]
#98 has been merged to resolve this issue. Will close this issue once 3.5.1 is 'feature-complete' and all merged issues can be tested at once.
