### ISSUE TITLE
Persistent Helicopter noise after mission end

### ISSUE THREAD

**Issue by ninjaProtocol** [Raptoer/F3#44]
The infamous bug. F3 or BI bug?

**Comment by SamLex** [comment]
Before we could even think about working out the cause, we would need a way to semi-reliably reproduce the bug. Which, last time I checked, no one has achieved

**Comment by SamLex** [comment]
A potentially 'fix' for this, since we have mpEnd anyway, would be to destroy all player-occupied helicopters at mission's end. Would probably want to eject them and make them invincible first to avoid triggering other endings, but that is details.

**Comment by shadow-fa** [comment]
Related ticket(s) in the BI feedback tracker:
- https://feedback.bistudio.com/T80726

**Comment by SamLex** [comment]
Closing due to the issue not being observed recently (mainly do to hosting countermeasures) and it being a BI bug anyway
