### ISSUE TITLE
Bring back F3 pre-mount component

### ISSUE THREAD

**Issue by ninjaProtocol** [Raptoer/F3#45]
F3 Pre-mount component was removed with 3.4.0 because a change in init order broke it. Will have to be shifted to init.sqf to work. Why do i want it? Has some benefits over Eden premount:
1. Unit types can be changed, unlike when mounted via eden
2. Vehicles can be changed safely without affecting crew
3. Easy to view changes to gear without having to drag units in and out of vehicles
4. Unaffected by unslotted units - fills vehicles with units available. Missing ASL doesn't mean truck has no driver!

Additional files that need to be added: none! preMount function still exists in FA F3.

Objects that need to be added to map template: Game logic objects called `F3_preMount_NATO`, `F3_preMount_NATO_1`, etc.

Proposed code to be added to init.sqf:
```sqf
// F3 - Premount component
// Shifted here from game logic init by SuicideKing
// Had to be shifted for compatibility with Eden

// refer to http://ferstaberinde.com/f3/en//index.php?title=PreMount_Component

// Excerpt from wiki:
// [[MyTruck1],["MyGroup1","MyGroup2"], boolean1, boolean2] call f_fnc_mountGroups;
// boolean1 - default is true  - all crew slots will be filled first (in order of: driver>gunner>commander>turrets) 
// boolean2 - default is false - A group won't be split up between synced vehicles

// comment out blocks you don't need
//F3_preMount_XXXX_Y referrs to game logics placed in template, sync them to target vehicles.

// (only runs server side)
if (isServer) then {

// NATO
/*
[synchronizedObjects F3_preMount_NATO,["GrpNATO_ASL","GrpNATO_A1","GrpNATO_A2"],false,false] call f_fnc_mountGroups;
[synchronizedObjects F3_preMount_NATO_1,["GrpNATO_BSL","GrpNATO_B1","GrpNATO_B2"],false,false] call f_fnc_mountGroups;
[synchronizedObjects F3_preMount_NATO_2,["GrpNATO_CSL","GrpNATO_C1","GrpNATO_C2"],false,false] call f_fnc_mountGroups;
[synchronizedObjects F3_preMount_NATO_3,["GrpNATO_CO","GrpNATO_DC"],true,false] call f_fnc_mountGroups;
*/

// FIA
/*
[synchronizedObjects F3_preMount_FIA,["GrpFIA_ASL","GrpFIA_A1","GrpFIA_A2"],false,false] call f_fnc_mountGroups;
[synchronizedObjects F3_preMount_FIA_1,["GrpFIA_BSL","GrpFIA_B1","GrpFIA_B2"],false,false] call f_fnc_mountGroups;
[synchronizedObjects F3_preMount_FIA_2,["GrpFIA_CSL","GrpFIA_C1","GrpFIA_C2"],false,false] call f_fnc_mountGroups;
[synchronizedObjects F3_preMount_FIA_3,["GrpFIA_CO","GrpFIA_DC"],true,false] call f_fnc_mountGroups;
*/

// CSAT

/*
[synchronizedObjects F3_preMount_CSAT,["GrpCSAT_ASL","GrpCSAT_A1","GrpCSAT_A2"],false,false] call f_fnc_mountGroups;
[synchronizedObjects F3_preMount_CSAT_1,["GrpCSAT_BSL","GrpCSAT_B1", "GrpCSAT_B2"],false,false] call f_fnc_mountGroups;
[synchronizedObjects F3_preMount_CSAT_2,["GrpCSAT_CSL","GrpCSAT_C1","GrpCSAT_C2"],false,false] call f_fnc_mountGroups;
[synchronizedObjects F3_preMount_CSAT_3,["GrpCSAT_CO","GrpCSAT_DC"],true,false] call f_fnc_mountGroups;
*/

// AAF
/*
[synchronizedObjects F3_preMount_AAF,["GrpAAF_ASL","GrpAAF_A1","GrpAAF_A2"],false,false] call f_fnc_mountGroups;
[synchronizedObjects F3_preMount_AAF_1,["GrpAAF_BSL","GrpAAF_B1","GrpAAF_B2"],false,false] call f_fnc_mountGroups;
[synchronizedObjects F3_preMount_AAF_2,["GrpAAF_CSL","GrpAAF_C1","GrpAAF_C2"],false,false] call f_fnc_mountGroups;
[synchronizedObjects F3_preMount_AAF_3,["GrpAAF_CO","GrpAAF_DC"],true,false] call f_fnc_mountGroups;
*/

};
```

**Comment by shadow-fa** [comment]
I would probably remove 3 of the 4 sides in the init.sqf to declutter it. Maybe add a comment to explain that other sides can be added?

Also: why not just synchronize the groups as well in eden? We could have something like this in init.sqf:
```sqf
[synchronizedObjects F3_preMount_NATO,false,false] call f_fnc_mountGroups;
```
and do the magic in the script.

**Comment by ninjaProtocol** [comment]
> Also: why not just synchronize the groups as well in eden? We could have something like this in init.sqf (...) and do the magic in the script.

Thanks for explaining this to me over Discord. You have my full support. 😄

**Comment by shadow-fa** [comment]
The preMount game logics were removed from the template in 3.4.0 because of a change or bug(?).

I tested the old method with the latest framework and latest Arma 3 1.76, and it seems to work (again?).
So maybe it was a bug that BIS fixed.
If someone can confirm this, I'd suggest to restore the preMount game logics from pre 3.4.0.
No other (code) changes are needed.

**Comment by SamLex** [comment]
#97 had been merged to resolve this issue. Will close this issue once 3.5.1 is 'feature-complete' and all merged issues can be tested at once.
