### ISSUE TITLE
SwS -> BIS revival

### ISSUE THREAD

**Issue by Raptoer** [Raptoer/F3#52]
Current problems:
1. Sometimes drag doesn't show up for those who are down
2. Death from down has caused this error before 
`
18:01:02   Error position: <_canUseMedikit && {!('FirstAidKit' in it>
18:01:02   Error Undefined variable in expression: _canusemedikit
18:01:02 File a3\functions_f_mp_mark\revive\fn_reviveAllowed.sqf [BIS_fnc_reviveAllowed], line 314`

**Comment by shadow-fa** [comment]
- JIP is broken. (we can't fix it and bohemia will never fix it) This might/will affect missions that rely on reinforcements.

**Comment by Raptoer** [comment]
2 open issues.
1. entering a vehicle while dragging causes problems
2. Sometimes dragger gets stuck (check combat pace)

**Comment by shadow-fa** [comment]
> entering a vehicle while dragging causes problems

Is this still an issue? @Raptoer

**Comment by Raptoer** [comment]
No

**Comment by SamLex** [comment]
Appears to have been resolved
