### ISSUE TITLE
Use a Git Subtree for ws_fnc

### ISSUE THREAD

**Issue by SamLex** [Raptoer/F3#65]

**Comment by shadow-fa** [comment]
Proposed steps:
1. We probably want to maintain our own ws_fnc (This means forking Wolfenswan's ws_fnc)
2. Update the new ws_fnc repository with all the changes that happened inside the F3 repository (While preserving commit history)
3. Use the new updated ws_fnc repository as a subtree inside F3
4. If ws_fnc things are changed within the F3 repository, then it should always be in a seperate commit (don't mix f3 and ws_fnc in one commit) for easier updating of the actual ws_fnc repository. We should not accept F3 Pull Requests if they mix ws_fnc and f3 within a single commit.

**Comment by shadow-fa** [comment]
Closing this for now due to lack of interest/urgency.
Maybe it will be re-opened later.
