### ISSUE TITLE
F3 nametags (WH) issues

### ISSUE THREAD

**Issue by shadow-fa** [Raptoer/F3#67]
Tweaks:
- In the map screen it still says "WH". Is this okay or do we want to change it?
- Maybe give the user settings to control the distances?
- `F_NT_SHOW_ROLE` should be set to `false`.

Errors/Issues:
- Sometimes (?) it throws an error because it can't get the location data properly.

**Comment by Quailsnap** [comment]
"WH" being there in any capacity is from the old version. I should have changed it all (back) to F / F3, and if I missed anything it's an accident.

I considered adding a sliding bar to determine how far names are seen for all players onscreen rather just the one under the cursor. Normally it's 50%, not counting the potential bonus to cursor tags from zooming in. Note that people increasing the distance at which all tags are visible means more nearEntities calls, more object caching, and more lost FPS.

Setting F_NT_SHOW_ROLE to false will still allow players to show roles with a toggle in the CBA settings, or briefing menu. It'll just change the default.

The 'location data' error might result from a spectator looking at his own fresh corpse (before it turns into a prop), or a player Zeus looking at his own body from a remote controlled unit.

**Comment by Quailsnap** [comment]
From #f3_fa:

> [14:42] Whale: Note that if you guys don't want to use roles (edit: with the new nametags, I mean) because your role names tend to be long, ie NATO Alpha 1 Fire Team Leader, you can always set the custom variable for Nametag Roles to make it more like A1 FTL if you want(edited)
[14:43] Whale: That could be in the gear script, actually
[14:47] Whale: Var is "f_var_assignGear_friendly"

**Comment by Quailsnap** [comment]
For my own reference tonight:
- Set config role to be default off
- Separate role and group disable in brief & CBA
- Take last accidental 'WH's out
- New pass on briefing menu, Y/N instead of toggles, color choices. Ensure persistence
- add "f_var_assignGear_friendly" (or alt) to all gear scripts

Other changes will come in a month or two when I revamp the whole system to use simpler caching, etc.

**Comment by SamLex** [comment]
Can this now be closed @shadow-fa?
