### ISSUE TITLE
Remove EandEcheck?

### ISSUE THREAD

**Issue by shadow-fa** [Raptoer/F3#73]
I analayzed all the missions from FAMDB and from my local cache and only found 9 missions use this component and I think it's trivial for any missionmaker to achieve the same functionality using a Trigger and one line of code.
e.g. something like this:
```sqf
({alive _x} count playableUnits) == ({alive _x && {_x in playableUnits}} count thisList)
```

But of course it doesn't hurt to leave the component in because it's tiny and might be useful for someone.

**Comment by ninjaProtocol** [comment]
I used it exactly once, the other time I had enough custom stuff going on that I just wrote my own version. So in that sense I agree it could go, however I'm of the mind that:
> But of course it doesn't hurt to leave the component in because it's tiny and might be useful for someone.

trumps the tiny space saving deleting it provides.

(That said, it can be dropped from the list of things we need to port to F4 for sure ;) )

**Comment by shadow-fa** [comment]
I would say we just close this issue and leave everything as it is,
**or** we remove it and clearly document - how to do the same thing with a trigger - on the [wiki](https://github.com/Raptoer/F3/wiki)

**Comment by SamLex** [comment]
Given its small size and the fact it isn't enabled by default, I think it can stay for now.
