### ISSUE TITLE
Enable dynamicViewDistance by default

### ISSUE THREAD

**Issue by shadow-fa** [Raptoer/F3#91]
Is there a reason why dynamicViewDistance is disabled by default?

**Comment by ninjaProtocol** [comment]
My problem with this is that the view distances can vary per mission, and as such infantry view distance is less than default server view distance. If you're enabling it by default, then the default infantry view distance in F3 DVD should be the same as the server view distance to avoid surprises for the mission maker.

EDIT: I'm assuming the reason it was off by default is that it runs in a loop in the background. And well, used to error out occasionally too. Shouldn't be a problem once we switch to the EH based system.

**Comment by SamLex** [comment]
The current default values are definitely provisional, and can be changed as needed.

Is it possible to get the default server view distance in SQF (config maybe? Or a scripting command?). If so, might make sense to set the infantry default to that and the others as multiples of that (e.g. vehicle distance is 1.5x, helicopter 3x, plane 5x, etc.).

Also, missionmakers can change the defaults as is required for a given mission.

**Comment by SamLex** [comment]
I wonder if executing `viewDistance` on the server will give that value. Could then be broadcast to clients with a public variable.

**Comment by SamLex** [comment]
Server view distance is 1600.

Suggested DVD defaults:
Default = 1600
Car = 2000
Tank = 2500
Rotary-wing = 3000
Fixed-wing = 5000

**Comment by SamLex** [comment]
#96 has been merged to resolve this issue. Will close this issue once 3.5.1 is 'feature-complete' and all merged issues can be tested at once.
