### ISSUE TITLE
Assign Gear: Distribute Insignia Separately

### ISSUE THREAD

**Issue by SamLex** [Raptoer/F3#95]
Currently insignias are taking up about ~10% (~100KB of 1MB) of the size of a PBO-ed version of the template. This seems like something of a waste of space considering how few insignias are used in any given mission: typically only one faction set is used and the 'higher' squads insignia's (Charlie and Juliet) are rarely used these days due to our lower player counts.

I propose the insignia files by moved out of the main template and distributed separately on a per-faction basis.

**Example**
Another Github repository could be used to host the insignia files, which would be ZIP files, one per-faction containing all the insignias for that faction. A mission maker could then download the appropriate one for the faction of the players in their mission and unpack those files into their mission.

Ideally this would be a drag-and-drop process, which would require some re-architecturing of assignGear. Given, however, that there is already a number of proposed assignGear proposals this could be performed during them if they go ahead.

**Comment by shadow-fa** [comment]
I don't think saving 100KB is worth the additional effort for missionmakers.
`ws_fnc` also takes up around 100KB and is rarely used,
but I think there's value in having these things directly in the framework, especially for new missionmakers.
If they weren't part of the framework, most missionmakers wouldn't even know that these things existed and so they would be used.

**Comment by SamLex** [comment]
Yeah, I can't actually remember why I thought to make this issue. After #94 I think the size of assignGear (the biggest component) will be greatly reduced and so any worries about file sizes I might have had will be eliminated.

Think I'll just close this.
